
image:
    pullPolicy: Always
imagePullSecrets:
    - name: github-registry

extraVolumeMounts:
  - name: tlscerts
    mountPath: /home/buildagent/.docker

extraVolumes:
  - name: tlscerts
    secret:
      secretName: cnt-builder
      defaultMode: 256
      items:
        - key: ca.crt
          path: ca.pem
        - key: tls.crt
          path: cert.pem
        - key: tls.key
          path: key.pem
