{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-agent
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.agent.extraFiles }}
  {{ $name }}: {{ $value | b64enc }}
{{- end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-agent-envs
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.agent.envs }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
