{{- if .Values.agent.enabled -}}
{{- if .Values.agent.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "teamcity.agent.serviceAccountName" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "teamcity.agent.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "teamcity.agent.serviceAccountName" . }}
{{- end }}
{{- end }}
