{{- if .Values.agent.enabled -}}
{{- if .Values.agent.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "teamcity.agent.serviceAccountName" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{ toYaml .Values.agent.rbac.rules }}
{{- end }}
{{- end }}
