{{- if and .Values.server.enabled (or .Values.server.configDb .Values.postgresql.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-db
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
data:
  database.properties: {{ include "teamcity.server.databaseProperties" . | b64enc }}
{{- end }}
