{{- if and .Values.server.enabled .Values.server.configDb -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-db
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
data:
  database.properties: {{ .Values.server.configDb | b64enc }}
{{- end }}
