name: Release

on:
  pull_request:
    branches:
      - master
      - release_2020.1.3-2
    # types: [closed]

env:
  CODE_TAG: ${{ github.head_ref::8 }}
  REGISTRY: docker.pkg.github.com/${{ github.repository }}

jobs:
  publish-release:
    needs: [build-release]
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && startsWith(github.head_ref, 'release_') && github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: '0'
      - name: Make tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CODE_TAG }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.head_ref }}
          release_name: Release ${{ github.head_ref }}
          body: |
            Release labels: ${{ join(github.event.pull_request.labels.*.name) }}

            docker pull ${{ env.REGISTRY }}/github-actions-runner:${{ env.CODE_TAG }}

          prerelease: "!startsWith(github.head_ref, 'release_')"

  build-release:
    runs-on: ubuntu-latest
    # if: github.base_ref == 'master' && startsWith(github.head_ref, 'release_') && github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Build
        run: make build
      - name: Github registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to github
        run: make push

      - name: Docker registry login
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: sergelog
          password: ${{ secrets.DOCKERIO_PASSWORD }}
      - name: Push images to docker hub
        run: make push
        env:
          REGISTRY: sergelog
